# Generated by Django 4.0.6 on 2022-08-01 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=15, null=True)),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account_type', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_origin', models.CharField(max_length=10, null=True)),
                ('Symbol', models.CharField(max_length=10, null=True)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('status', models.CharField(max_length=15, null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('currency', models.CharField(max_length=15, null=True)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('number', models.IntegerField()),
                ('code', models.CharField(max_length=10, null=True)),
                ('transaction_type', models.CharField(max_length=15)),
                ('transaction_charge', models.IntegerField()),
                ('Receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
                ('Wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('currency', models.IntegerField()),
                ('transaction_cost', models.IntegerField(default=1)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_reciepient', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_type', models.CharField(max_length=15, null=True)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
                ('receipt_number', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, null=True)),
                ('message', models.CharField(max_length=15, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=6, null=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(null=True)),
                ('loan_intrest', models.IntegerField(null=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime.now)),
                ('loan_ID', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=15, null=True)),
                ('loan_status', models.CharField(max_length=15, null=True)),
                ('date_issued', models.DateTimeField(default=datetime.datetime.now)),
                ('balance', models.IntegerField(null=True)),
                ('guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=15, null=True)),
                ('card_number', models.IntegerField()),
                ('date', models.IntegerField()),
                ('card_type', models.CharField(max_length=10, null=True)),
                ('expiry_date', models.DateTimeField(default='')),
                ('security_code', models.IntegerField(default='')),
                ('issuer', models.CharField(max_length=15, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.account')),
            ],
        ),
    ]
