# Generated by Django 4.0.6 on 2022-08-01 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='card',
            name='date',
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='security_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_reciepient',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
