# Generated by Django 4.0.6 on 2022-08-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_delete_currency_remove_card_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
