# Generated by Django 4.0.6 on 2022-08-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_rename_wallet_transaction_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reciept',
            name='receipt_number',
        ),
        migrations.AlterField(
            model_name='reward',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
