# Generated by Django 4.0.6 on 2022-08-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_remove_reciept_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_origin', models.CharField(max_length=10, null=True)),
                ('Symbol', models.CharField(max_length=10, null=True)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transaction', to='Wallet.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='Reciept',
        ),
    ]
