# Generated by Django 4.0.6 on 2022-08-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0006_transaction_destination_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Receipt',
            new_name='receipt',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
